import type { Metadata } from 'next';
import Link from 'next/link';
import './globals.css';

export const metadata: Metadata = {
	title: 'Face & Hand Tracker',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className='relative'>
				<nav className='absolute z-20 mt-10 flex flex-row space-y-3 text-blue-500'>
					<Link className='hover:underline bg-blue-100 p-2 rounded text-center' href='/'>
						Face Landmarks
					</Link>
					<Link className='hover:underline bg-blue-100 p-2 rounded text-center' href='/hand-landmarks'>
						Hand Landmarks
					</Link>
					<Link className='hover:underline bg-blue-100 p-2 rounded text-center' href='/hand-brightness'>
						Hand Brightness
					</Link>
				</nav>
				{children}
			</body>
		</html>
	);
}
